<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Academic Assignment Application - PDF</title>
    <style>
    body {
        font-family: DejaVu Sans, Arial, sans-serif;
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
        line-height: 1.6;
        color: #333;
    }

    .header {
        text-align: center;
        margin-bottom: 30px;
        border-bottom: 2px solid #007bff;
        padding-bottom: 15px;
    }

    .application-details {
        background-color: #f8f9fa;
        padding: 20px;
        border-radius: 8px;
        margin-bottom: 30px;
        border-left: 4px solid #007bff;
    }

    .details {
        margin-bottom: 12px;
        display: flex;
        align-items: center;
    }

    .details strong {
        display: inline-block;
        width: 180px;
        color: #495057;
        font-weight: 600;
    }

    .details span {
        flex: 1;
        padding: 5px 10px;
        background-color: white;
        border-radius: 4px;
        border: 1px solid #dee2e6;
    }

    .form-section {
        margin-bottom: 25px;
    }

    .assignment-content {
        background-color: white;
        padding: 25px;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    .dotted-line {
        border-bottom: 1px dotted #000;
        display: inline-block;
        min-width: 200px;
        margin: 0 5px;
    }

    .instructions {
        margin: 20px 0;
        padding: 20px;
        background-color: #e3f2fd;
        border-left: 4px solid #2196f3;
        border-radius: 4px;
    }

    .answer-section {
        margin-top: 30px;
        padding: 20px;
        background-color: #f5f5f5;
        border-radius: 8px;
    }

    .signature-section {
        margin-top: 40px;
        display: flex;
        justify-content: space-between;
        padding-top: 20px;
        border-top: 1px solid #dee2e6;
    }

    .status-badge {
        display: inline-block;
        padding: 4px 12px;
        border-radius: 20px;
        font-size: 12px;
        font-weight: bold;
        text-transform: uppercase;
    }

    .status-approved {
        background-color: #d4edda;
        color: #155724;
    }

    .status-pending {
        background-color: #fff3cd;
        color: #856404;
    }

    .status-rejected {
        background-color: #f8d7da;
        color: #721c24;
    }

    @media print {
        body {
            font-size: 12px;
        }

        .no-print {
            display: none;
        }
    }
    </style>
</head>

<body>
    <div class="header">
        <h1>Academic Assignment Application</h1>
        <p style="color: #6c757d; margin: 5px 0;">Bachelor of Education in Primary Education</p>
    </div>

    <!-- Application Details Section -->
    <div class="application-details">
        <h2 style="margin-top: 0; color: #007bff;">Application Details</h2>

        <div class="details">
            <strong>Application ID:</strong>
            <span>{{ $application->id }}</span>
        </div>

        <div class="details">
            <strong>Student Name:</strong>
            <span>{{ $application->user->user_name }}</span>
        </div>

        <div class="details">
            <strong>Registration Number:</strong>
            <span>{{ $application->user->reg_no }}</span>
        </div>

        <div class="details">
            <strong>Application Status:</strong>
            <span class="status-badge status-{{ strtolower($status->status) }}">
                {{ $status->status }}
            </span>
        </div>

        <div class="details">
            <strong>Course Code:</strong>
            <span>KDU/LIB/{{ $application->course_code ?? '001' }}</span>
        </div>

        <div class="details">
            <strong>Academic Year:</strong>
            <span>{{ date('Y') }}/{{ date('m') }}/{{ date('d') }}</span>
        </div>

        <div class="details">
            <strong>PDF Reason/Info:</strong>
            <span>{{ $pdf_reason }}</span>
        </div>

        <div class="details">
            <strong>Generated By:</strong>
            <span>{{ $user->name }}</span>
        </div>

        <div class="details">
            <strong>Generated At:</strong>
            <span>{{ now()->format('Y-m-d H:i:s') }}</span>
        </div>
    </div>

    <!-- Assignment Content Section -->
    <div class="assignment-content">
        <div class="form-section">
            <h2>Assignment Information</h2>
            <p><strong>Subject:</strong> Primary Education</p>
            <p><strong>Course:</strong> Bachelor of Education in Primary Education</p>
            <p><strong>Assignment Topic:</strong>
                {{ $application->assignment_topic ?? 'Educational Psychology and Learning Theories' }}
            </p>
        </div>

        <div class="instructions">
            <h3>Assignment Instructions</h3>
            <p>{{ $application->instructions ?? 'Write about educational psychology and learning theories. Discuss different learning approaches such as behavioral, cognitive, constructivist, and social learning theories. Explain how these theories can be applied in primary education settings.' }}
            </p>
        </div>

        <div class="form-section">
            <h3>Assignment Description</h3>
            <p>{{ $application->description ?? 'Answer the questions about educational theories, learning processes, and teaching methods. Provide examples of how different learning theories can be implemented in classroom settings to enhance student learning and development.' }}
            </p>
        </div>

        @if($application->answers ?? false)
        <div class="answer-section">
            <h3>Student Answers</h3>
            @foreach(json_decode($application->answers, true) as $index => $answer)
            <div class="form-section">
                <strong>{{ $index + 1 }}.</strong>
                <p style="margin-left: 20px; padding: 10px; background-color: white; border-radius: 4px;">
                    {{ $answer }}
                </p>
            </div>
            @endforeach

            @if($application->additional_answers)
            <div class="form-section">
                <strong>Additional Answers:</strong>
                <p style="margin-left: 20px; padding: 10px; background-color: white; border-radius: 4px;">
                    {{ $application->additional_answers }}
                </p>
            </div>
            @endif
        </div>
        @endif

        <div class="signature-section">
            <div style="text-align: center;">
                <div style="border-bottom: 1px solid #000; width: 200px; margin-bottom: 5px;"></div>
                <p><strong>Student Signature</strong></p>
                <p><small>{{ $application->user->user_name }}</small></p>
                <p><small>Date: {{ $application->created_at->format('Y-m-d') }}</small></p>
            </div>

            <div style="text-align: center;">
                <div style="border-bottom: 1px solid #000; width: 200px; margin-bottom: 5px;"></div>
                <p><strong>Instructor Signature</strong></p>
                <p><small>{{ $user->name }}</small></p>
                <p><small>Date: {{ now()->format('Y-m-d') }}</small></p>
            </div>
        </div>
    </div>

    <!-- Footer Information -->
    <div
        style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #dee2e6; text-align: center; color: #6c757d; font-size: 12px;">
        <p>This document was automatically generated by the Academic Management System</p>
        <p>Generated on {{ now()->format('F j, Y \a\t g:i A') }}</p>
        @if($application->updated_at != $application->created_at)
        <p>Last updated: {{ $application->updated_at->format('F j, Y \a\t g:i A') }}</p>
        @endif
    </div>
</body>

</html>